export const DUMMY_RESPONSES = [
  "Hello! How can I assist you today?",
  "I'm here to help! What do you need?",
  "Please tell me how I can be of service.",
  "Sure, I can help with that! What do you need?",
  "I'm on it! Just give me the details.",
  "Absolutely! What can I do for you?",
  "I'm here to support you. What can I do?",
  "Let's get started! How can I assist?",
  "I can handle that for you. What’s the task?",
  "Ready to help! What would you like to know?",
  "Sure, I'll do my best to assist you. What can I help you with?",
  "No problem! How can I be of service?",
  "I'm ready to assist you. What do you need help with?",
  "Count on me to help you out. What's your request?",
  "I'm here to support you. How can I assist you today?",
  "Absolutely! Let me know what you need help with.",
  "I'm at your service. What can I do for you?",
  "Happy to help! What can I assist you with?",
  "Consider it done! What's the task at hand?",
  "I'm here to lend a hand. What do you need assistance with?",
  "Ready to assist! What would you like to know?",
  "Leave it to me! How can I assist you?",
  "I'm here to help. What can I do for you?",
  "No worries! How can I assist you today?",
  "I'm all ears. What do you need help with?",
  "Sure thing! What can I do for you?",
  "Let me know how I can assist you.",
  "I'm here to support you. What do you need help with?",
  "Absolutely! How can I be of service?",
  "I'm ready to help. What do you need assistance with?",
  "Consider it done! What can I assist you with?",
  "I'm at your service. What can I do for you?",
  "Happy to help! What's your request?",
  "No problem! How can I assist you today?",
  "I'm here to lend a hand. What do you need help with?",
  "Sure, I'll do my best to assist you. What do you need?",
  "I'm here to support you. What can I do for you?",
  "Absolutely! Let me know what you need help with.",
  "I'm ready to assist you. What's your request?",
  "Count on me to help you out. How can I assist you?",
  "I'm at your service. What can I do for you?",
  "Consider it done! What's the task at hand?",
  "I'm here to lend a hand. What do you need assistance with?",
  "Ready to assist! What would you like to know?",
  "Leave it to me! How can I assist you?",
  "I'm here to help. What can I do for you?",
  "No worries! How can I assist you today?",
  "I'm all ears. What do you need help with?",
  "Sure thing! What can I do for you?",
  "Let me know how I can assist you.",
  "I'm here to support you. What do you need help with?",
  "Absolutely! How can I be of service?",
  "I'm ready to help. What do you need assistance with?",
  "Consider it done! What can I assist you with?",
  "I'm at your service. What can I do for you?",
  "Happy to help! What's your request?",
  "No problem! How can I assist you today?",
  "I'm here to lend a hand. What do you need help with?",
  "Sure, I'll do my best to assist you. What do you need?",
  "I'm here to support you. What can I do for you?",
  "Absolutely! Let me know what you need help with.",
  "I'm ready to assist you. What's your request?",
  "Count on me to help you out. How can I assist you?",
  "I'm at your service. What can I do for you?",
  "Consider it done! What's the task at hand?",
  "I'm here to lend a hand. What do you need assistance with?",
  "Ready to assist! What would you like to know?",
  "Leave it to me! How can I assist you?",
  "I'm here to help. What can I do for you?",
  "No worries! How can I assist you today?",
  "I'm all ears. What do you need help with?",
  "Sure thing! What can I do for you?",
  "Let me know how I can assist you.",
];

export const FIRST_BOT_MESSAGE =
  "Hello!, This is a dummy bot designed to test your development skills. Please type 'error' to make the bot throw an error. Otherwise, type anything else to get a random response from the bot.";
